name: Artifact Consumer

on:
  workflow_run:
    workflows: ["Artifact Example workflow"]
    types:
      - completed

jobs:
  consume-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Wait before downloading
        run: sleep 30  # Wait 30 seconds before downloading
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Displaying content 
        run: cat message.txt
